### ISSUE TITLE
Missing example for BuyerFrontEnd load testing

### ISSUE THREAD

**Issue by fhoering** [privacysandbox/bidding-auction-servers#28]
Currently [the load testing example](https://github.com/privacysandbox/bidding-auction-servers/blob/main/tools/load_testing/README.md) is provided for the seller only. 

One difference between SFE and BFE is that the BFE is deployed as pure GRPC endpoint without the Envoy proxy that exposes endpoints via HTTP1. So as of now wrk2 seems to only work with the SellerFrontEnd as it only seems to support HTTP1 (https://github.com/giltene/wrk2) and the query actually uses JSON (`wrk.headers["Content-Type"] = "application/json"`).

My understanding is that GRPC is a protocol of Protobuf queries/replies over HTTP2 (see https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md). So in theory I would expect that it is possible to just craft binary Proto requests and send them over the wire via HTTP2 (it is unclear to me if wrk2 can support HTTP2)

As a first experiment I tried to inject binary proto messages with curl via HTTP2 as indicated in this blog post  [grpc with curl](https://blog.salrashid.dev/articles/2017/grpc_curl/) without success:

`@encrypted_payload` is the binary format of a payload for [GetBidRequest](https://github.com/privacysandbox/bidding-auction-servers/blob/332e46b216bfa51873ca410a5a47f8bec9615948/api/bidding_auction_servers.proto#L392)

```
curl -v -H "Content-Type: application/grpc" -H "TE: trailers" \
-H "X-User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36" \
-H "x-accept-language: en-US,en;q=0.9" -H "X-BnA-Client-IP: 1.1.1.1" \
--data-binary "@encrypted_payload"  https://adtech.com/v1/getbids
```

It fails with

```
< HTTP/2 200
< server: awselb/2.0
< date: Thu, 12 Dec 2024 12:11:24 GMT
< content-type: application/grpc
< content-length: 0
< grpc-status: 12
```

Any advice on how to get this working to be able to send several 1000s of QPS to the BFE ?

**Comment by salmanmlk** [comment]
Hi Fabian,

You could test a single request via [`grpcurl`](https://github.com/fullstorydev/grpcurl). Example execution:

```
grpcurl --plaintext -H 'X-BnA-Client-IP:1.1.1.1' -H 'X-User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36' -H 'x-accept-language: en-US,en;q=0.9' -d '@' localhost:50051 privacy_sandbox.bidding_auction_servers.BuyerFrontEnd/GetBids < /tmp/encrypted_payload.txt
```

Note:
- I used `localhost:50051` since I was sending the request to a local stack and thus also had to add `--plaintext` since local stack doesn't run with TLS. You will need to remove plaintext option and set the GRPC service address e.g. dns:///<grpc-host-name> 
- You can also wrap this into a bash script with a loop and run the requests async.


Alternatively, You could look into [ghz](https://github.com/bojand/ghz/releases) for sending bulk traffic. Once `ghz` is installed, here is an example command to send traffic:

```
ghz --config config.json
```

Where my config looked as follows:

```
{                                                                                  
  "name": "Buyer stack load test",                                
  "call": "privacy_sandbox.bidding_auction_servers.BuyerFrontEnd/GetBids",         
  "total": 2000,                                                                   
  "rps": 1000,                                                                     
  "concurrency": 128,                                                              
  "metadata": {                                                                    
    "x-bna-client-ip": "1.1.1.1",                                           
    "x-accept-language": "en-US,en;q=0.9",                                         
    "x-user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"
  },                                                                               
  "host": "localhost:50051",                                                       
  "insecure": true,                                                                
  "enable-compression": false,                                                     
  "async": true,                                                                   
  "data-file": "/tmp/encrypted_payload.txt"                                        
} 
```

Note:
- I set concurrency to number of CPUs I had so please adjust according to your machine.
- I had also set "insecure" param since I was testing against local stack and thus you will need to toggle this and set `host` appropriate to your stack config.
- Of course feel free to experiment with other options as needed.


Finally I have assumed here that you have an encrypted payload at hand but if not, you could create encrypted request to feed to above tools using [secure_invoke](https://github.com/privacysandbox/bidding-auction-servers/tree/main/tools/secure_invoke#secure-invoke-tool), here is a sample command:

```
# After building secure invoke
bazel-bin/tools/secure_invoke/invoke --input_file=requests/plaintext_request.json --op=encrypt  --target_service=BFE > /tmp/encrypted_payload.txt
```

**Comment by chatterjee-priyanka** [comment]
Thanks @salmanmlk.  Thanks @fhoering for filing the issue.

The primary problem with gHz is that it batches requests and given the request includes headers as metadata (due to metadata forwarding in B&A) that total size of header may exceed gRPC channel's size limit. The default channel limit for metadata is [16 KB] currently (https://github.com/grpc/grpc/blob/0498194240f55d7f4b12633ad01339fb690621bf/include/grpc/impl/channel_arg_names.h#L196) 

In the past, we have seen this issue with 500-1000 QPS with gHZ during load test, I can not remember if the gRPC channel limit was much smaller than 16 KB. The limit is configurable and can be set higher but there are downsides to that, and gRPC generally doesn't recommend setting higher. 

@fhoering 
As Salman presented above, hitting BFE directly with 1000 QPS works. This depends on the total size of metadata forwarded for a batch of requests, you should be good if that is <16 KB.

I agree wrk2 is an overhead to load test buyer B&A stacks given Envoy needs to be configured in front of BFE. We will update the documentation to make this clearer.

**Comment by salmanmlk** [comment]
I have added load test instructions for buyer in the README (along with caveats for metadata size and the effect of proxies in between the path from client to server). The update will be available in next release (tentatively planned for early January).

Will close this now. Feel free to open a new one if you need anything else here.
